AllCops:
  Exclude:
    - 'spec/spec_helper.rb'

Naming/MethodParameterName:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/AbcSize:
  Enabled: false